export const FETCH_TODOS_LOADING = 'FETCH_TODOS_LOADING';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const TOGGLE_TODO_LOADING = 'TOGGLE_TODO_LOADING';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR';


export const CLEAR_TODO_LOADING = 'CLEAR_TODO_LOADING';
export const CLEAR_TODO_SUCCESS = 'CLEAR_TODO_SUCCESS';
export const CLEAR_TODO_ERROR = 'CLEAR_TODO_ERROR';
